### ISSUE TITLE
Black Frame in some images for a while

### ISSUE THREAD

**Issue by wariobar** [plaidman/retromega-next#1]
Hi, I'm experiencing some black frames in images sometimes when I am moving from one game to anther. Not always happens and right after the images are displayed well as they are. I didn't have this issue with retro mega before.

Thanks a lot!!

![IMG_20220207_131731](https://user-images.githubusercontent.com/46299677/152796145-395db029-9ed5-4a4a-9188-49626c293681.jpg)
![IMG_20220207_131801](https://user-images.githubusercontent.com/46299677/152796148-40d349d1-1e42-4f44-a69e-833034b0d938.jpg)
![IMG_20220207_131955](https://user-images.githubusercontent.com/46299677/152796152-371bbcc9-4f37-4ece-a688-b613db1245e6.jpg)
![IMG_20220207_131932](https://user-images.githubusercontent.com/46299677/152796153-001300ab-6036-48a0-b3b0-ab52f509a555.jpg)

**Comment by plaidman** [comment]
interesting, thanks for the report. I suspect it's a problem when it tries to load the image and for some reason fails. When this happens it should remove the black box, shadow, and the cached image that you're seeing when you highlight over a game but it still shows the previous image. Can you do me a favor and zip up your sega-cd media folder and post them here?

**Comment by wariobar** [comment]
[media.zip](https://github.com/plaidman/retromega-next/files/8018847/media.zip)

Sure thing, here you go!  Yes, it does look like cache issue.  It happens also with other games from other consoles/folders, in case is needed I can record a video. Thanks!

**Comment by plaidman** [comment]
@wariobar I have an update that might fix your issue. would you mind testing this:
[mediatest.zip](https://github.com/plaidman/retromega-next/files/8054457/mediatest.zip)

**Comment by wariobar** [comment]
Great! I'll try it once a have a moment. I'll keep you posted. Thanks a lot!!

**Comment by plaidman** [comment]
awesome, thanks! I updated it so the shadow is generated, instead of a background image, that should get rid of the black border. I also simplified the scaling logic to hopefully solve an issue where the image loads but doesn't display.

**Comment by wariobar** [comment]
It works!! Black frames are gone. I didn't have a lot of time for testing, but so far so good. I didn't see any side efects of this fix.

Thanks a lot! '
Mario

**Comment by plaidman** [comment]
Glad to hear it. I'll close this for now, feel free to reopen it or add a new one if you find anything else. Thanks for testing!
