### ISSUE TITLE
Gamelist lag due to immediate image retrieval

### ISSUE THREAD

**Issue by SireSalty** [plaidman/retromega-next#10]
Please add a 50-200 ms delay in loading image artwork within gamelists.  Without artwork, the lists work without any issue whatsoever, once image is added lag is immense when scrolling large lists.   Does not need to affect pre-existing video delays or anything with the details screen.  (retroid pocket 2+ as test device)

Without images:  https://youtube.com/shorts/w_1zsxh7Wno
With Images (holding down the down arrow):  https://www.youtube.com/shorts/YqxCEGZ9UHk

**Comment by SireSalty** [comment]
Appears related to https://github.com/mmatyas/pegasus-frontend/issues/937

**Comment by plaidman** [comment]
updated!
