### ISSUE TITLE
Multiplayer filter

### ISSUE THREAD

**Issue by costuwpisze** [plaidman/retromega-next#11]
Hi, is it possible to add multiplayer filter? I dont think super precise filtering (like "choose 2 or 3 or 4 players") is needed, but "2+" filter would be nice and useful to play with friends ;) And maybe info about number of players in game details.

I love your project, the best theme from many i've tried <3 Thank you!

**Comment by plaidman** [comment]
update: this feature is ready to go for the next release

**Comment by plaidman** [comment]
gonna keep this open until the release =)

**Comment by plaidman** [comment]
@costuwpisze it's been released! enjoy
