### ISSUE TITLE
Video sound plays after details view

### ISSUE THREAD

**Issue by wariobar** [plaidman/retromega-next#12]
Hi, here you go.Repro steps:

- Go to details view for a game
- Wait until the video plays
- Go back to the game list view
- In the game list view you still can listen the sound playing from the video played in details view when you see the box image
- Even if you go up or down in the game list view and wait a bit until another the video is played, so you listen the sound of two videos at the same time

Let me know in case you need anything else from my end. Many thanks!! This theme is awesome

Mario

**Comment by plaidman** [comment]
it's on my list. thanks for the report!

**Comment by plaidman** [comment]
this is fixed in dev. just waiting on testing for a different thing before I cut a new release. probably tomorrow.
