### ISSUE TITLE
Xbox style key

### ISSUE THREAD

**Issue by youkoseki** [plaidman/retromega-next#17]
With Retroid now supports Xbox style keymap (swap a/b and x/y), is it possible to support that key style as well? Theme works perfectly as it is, but footer icons need to be updated accordingly (B to play, A to back etc). I can manually edited some Component.qml files, but it would be great if it is officially supported by having a switch option on the setting.

**Comment by plaidman** [comment]
not a bad idea. I'll add it to the list.

**Comment by plaidman** [comment]
this feature was added in the latest version =)
