### ISSUE TITLE
Scaling theme to 1080p

### ISSUE THREAD

**Issue by dontblush** [plaidman/retromega-next#2]
I'm using this theme on the PC, I was wondering how to scale it to 1080p

**Comment by plaidman** [comment]
It should automatically scale to any resolution but the font and image sizes will increase to match. If you're looking to make the font smaller, this will require some code modification. I think I can add a todo item for the next release to add a small font setting option.

**Comment by plaidman** [comment]
If you don't want to wait for an update, you can change [this line](https://github.com/plaidman/retromega-next/blob/main/components/footer/Component.qml#L12) and [this line] to `root.height * 0.065` and change [this line](https://github.com/plaidman/retromega-next/blob/main/components/gameList/GameScroll.qml#L6) to `gamesListView.height * 0.06`

**Comment by dontblush** [comment]
Thx for the reply, I'll tinker with the lines you mentioned but I will also wait for the update

**Comment by plaidman** [comment]
just to follow up on this, the most recent update includes an option to switch to a smaller font size for larger screens.
