### ISSUE TITLE
Vídeos Not Play, Only Audio 

### ISSUE THREAD

**Issue by leocmp** [plaidman/retromega-next#4]
Hello, I'm using the latest version of pegasus, and theme and the videos only output the audio, in the other themes the video runs normally, I'm using Android 12

**Comment by plaidman** [comment]
Someone else on the discord was having a similar issue with a different theme. Can you try something for me?

1. change [this line](https://github.com/plaidman/retromega-next/blob/main/components/media/GameVideo.qml#L70) to `visible: true;`
2. add `visible: false;` somewhere in [these lines](https://github.com/plaidman/retromega-next/blob/main/components/media/GameVideo.qml#L81-L87)

If this works, I may have you try some extra steps to find a better solution that that. Unfortunately I haven't found anybody else with this issue so you might have to be my test subject to solve this for anybody else.

**Comment by leocmp** [comment]
Thanks for the feedback, it worked changing the points you mentioned.

**Comment by leocmp** [comment]
If you need my help for a test and just say

**Comment by plaidman** [comment]
ok I have some more time now to start working on retromega again. if you have some time to test, I have some things you can try. first can you try setting `visible: true;` in both the Video and DropShadow sections in the file I linked before?

**Comment by leocmp** [comment]
Hello, sorry for the test delay, I was traveling, I took the test here and the videos continue to work normally, setting two options to true.

**Comment by plaidman** [comment]
Awesome! And when both are true you see a shadow underneath the video right?

**Comment by leocmp** [comment]
![Screenshot_20220329-195208](https://user-images.githubusercontent.com/78039/160719581-52095a9f-5cdd-4e8f-8ba3-064e2eec114b.png)
Hello, I did the test you asked for but the video didn't have the shadow. Here's a picture of how it turned out

**Comment by leocmp** [comment]
![Screenshot_20220329-195135_RS File Manager](https://user-images.githubusercontent.com/78039/160719762-a1074d30-8433-47a4-9869-8c1bb9e41ad3.png)

**Comment by plaidman** [comment]
ok, thanks for the report. I think I'm gonna get rid of dropshadows for everything, it's ending up being a performance hit that I don't really care for. maybe I'll make it a setting or something. Thanks for testing!

**Comment by plaidman** [comment]
to close out this issue, I added an option in the newest update to disable dropshadow. that should resolve this issue. feel free to reopen if it doesn't.
