### ISSUE TITLE
Random game not selected correctly

### ISSUE THREAD

**Issue by alexb78** [plaidman/retromega-next#6]
The random function allows to select a random game from the games list. However the random game is not selected correctly  because pressing UP or DOWN again jumps back and X opens the game selected previously. Would really appreciate if you could fix this, Thanks for the great work!

**Comment by plaidman** [comment]
Yep, you're right. I see the issue exactly. This will be fixed in the next release

**Comment by plaidman** [comment]
in the mean time, if you want a quick fix yourself, you can change [this line](https://github.com/plaidman/retromega-next/blob/main/components/gameList/Component.qml#L56) to `updateGameIndex(randomIndex);`

I'll leave this issue open until the fix is in the next release

**Comment by alexb78** [comment]
Thank you for that quick resolution. It is working fine now.
