### ISSUE TITLE
Recent played games

### ISSUE THREAD

**Issue by plaidman** [plaidman/retromega-next#8]
This collection seems off. Lists random games

**Comment by dollerbill** [comment]
Confirmed, only two games displaying under Recent and both are titles that haven't been launched since well before the update

**Comment by plaidman** [comment]
I have a fix ready to go for the next release. you can apply it manually if you want by replacing [these lines](https://github.com/plaidman/retromega-next/blob/28apr2022/theme.qml#L148-L159) in `/theme.qml` with [these lines](https://github.com/plaidman/retromega-next/blob/main/theme.qml#L148-L167)

**Comment by plaidman** [comment]
this is fixed in the latest release @dollerbill
