### ISSUE TITLE
Type Sorting.Component unavailable

### ISSUE THREAD

**Issue by wariobar** [plaidman/retromega-next#9]
Hi,
For some reason the theme is not being loaded in my RP2's pegasus. Below you can find my lastrun.log

[lastrun.log](https://github.com/plaidman/retromega-next/files/8603696/lastrun.log)

I couldnt try the 1st April release, but the previous one worked fine. My pegasus is able to load other themes.
Any idea on what is happening?
 
Many thanks!

Regards,
Mario

**Comment by plaidman** [comment]
The real error is on this line: `SortingScroll.qml:2:1: module "Qt.labs.qmlmodels" is not installed.` I wonder if you're using an older version of Pegasus that doesn't include the qmlmodels package. Can you do me a favor and see if it's in the latest stable (which was updated within the last month), and if not, check if it's in the latest nightly build.
